/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database.routines;


import com.csc680.orbit.database.Orbit;

import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoadRoles extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1193987722;

    /**
     * Create a new routine call instance
     */
    public LoadRoles() {
        super("load_roles", Orbit.ORBIT);
    }
}
