/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database.tables;


import com.csc680.orbit.database.Indexes;
import com.csc680.orbit.database.Keys;
import com.csc680.orbit.database.Orbit;
import com.csc680.orbit.database.tables.records.AccountLinkTeacherRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountLinkTeacher extends TableImpl<AccountLinkTeacherRecord> {

    private static final long serialVersionUID = 1973584421;

    /**
     * The reference instance of <code>orbit.account_link_teacher</code>
     */
    public static final AccountLinkTeacher ACCOUNT_LINK_TEACHER = new AccountLinkTeacher();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountLinkTeacherRecord> getRecordType() {
        return AccountLinkTeacherRecord.class;
    }

    /**
     * The column <code>orbit.account_link_teacher.ID</code>.
     */
    public final TableField<AccountLinkTeacherRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>orbit.account_link_teacher.Date_Linked</code>.
     */
    public final TableField<AccountLinkTeacherRecord, Date> DATE_LINKED = createField("Date_Linked", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>orbit.account_link_teacher.Active</code>.
     */
    public final TableField<AccountLinkTeacherRecord, String> ACTIVE = createField("Active", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>orbit.account_link_teacher.User_ID</code>.
     */
    public final TableField<AccountLinkTeacherRecord, Integer> USER_ID = createField("User_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>orbit.account_link_teacher.Teacher_ID</code>.
     */
    public final TableField<AccountLinkTeacherRecord, Integer> TEACHER_ID = createField("Teacher_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>orbit.account_link_teacher</code> table reference
     */
    public AccountLinkTeacher() {
        this(DSL.name("account_link_teacher"), null);
    }

    /**
     * Create an aliased <code>orbit.account_link_teacher</code> table reference
     */
    public AccountLinkTeacher(String alias) {
        this(DSL.name(alias), ACCOUNT_LINK_TEACHER);
    }

    /**
     * Create an aliased <code>orbit.account_link_teacher</code> table reference
     */
    public AccountLinkTeacher(Name alias) {
        this(alias, ACCOUNT_LINK_TEACHER);
    }

    private AccountLinkTeacher(Name alias, Table<AccountLinkTeacherRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountLinkTeacher(Name alias, Table<AccountLinkTeacherRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Orbit.ORBIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCOUNT_LINK_TEACHER_ACCOUNT_LINK_TEACHER_IBFK_2, Indexes.ACCOUNT_LINK_TEACHER_ACCOUNT_LINK_USER_IBFK_1, Indexes.ACCOUNT_LINK_TEACHER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AccountLinkTeacherRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACCOUNT_LINK_TEACHER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccountLinkTeacherRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_LINK_TEACHER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccountLinkTeacherRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountLinkTeacherRecord>>asList(Keys.KEY_ACCOUNT_LINK_TEACHER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AccountLinkTeacherRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AccountLinkTeacherRecord, ?>>asList(Keys.ACCOUNT_LINK_USER_IBFK_1, Keys.ACCOUNT_LINK_TEACHER_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacher as(String alias) {
        return new AccountLinkTeacher(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacher as(Name alias) {
        return new AccountLinkTeacher(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountLinkTeacher rename(String name) {
        return new AccountLinkTeacher(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountLinkTeacher rename(Name name) {
        return new AccountLinkTeacher(name, null);
    }
}
