/*
 * This file is generated by jOOQ.
*/
package database.tables;


import database.Indexes;
import database.Keys;
import database.Orbit;
import database.tables.records.PictureRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Picture extends TableImpl<PictureRecord> {

    private static final long serialVersionUID = -424944774;

    /**
     * The reference instance of <code>orbit.picture</code>
     */
    public static final Picture PICTURE = new Picture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PictureRecord> getRecordType() {
        return PictureRecord.class;
    }

    /**
     * The column <code>orbit.picture.ID</code>.
     */
    public final TableField<PictureRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>orbit.picture.Year</code>.
     */
    public final TableField<PictureRecord, String> YEAR = createField("Year", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>orbit.picture.Picture</code>.
     */
    public final TableField<PictureRecord, byte[]> PICTURE_ = createField("Picture", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>orbit.picture.Student_ID</code>.
     */
    public final TableField<PictureRecord, Integer> STUDENT_ID = createField("Student_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>orbit.picture</code> table reference
     */
    public Picture() {
        this(DSL.name("picture"), null);
    }

    /**
     * Create an aliased <code>orbit.picture</code> table reference
     */
    public Picture(String alias) {
        this(DSL.name(alias), PICTURE);
    }

    /**
     * Create an aliased <code>orbit.picture</code> table reference
     */
    public Picture(Name alias) {
        this(alias, PICTURE);
    }

    private Picture(Name alias, Table<PictureRecord> aliased) {
        this(alias, aliased, null);
    }

    private Picture(Name alias, Table<PictureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Orbit.ORBIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PICTURE_PRIMARY, Indexes.PICTURE_STUDENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PictureRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PictureRecord> getPrimaryKey() {
        return Keys.KEY_PICTURE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PictureRecord>> getKeys() {
        return Arrays.<UniqueKey<PictureRecord>>asList(Keys.KEY_PICTURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PictureRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PictureRecord, ?>>asList(Keys.PICTURE_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Picture as(String alias) {
        return new Picture(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Picture as(Name alias) {
        return new Picture(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Picture rename(String name) {
        return new Picture(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Picture rename(Name name) {
        return new Picture(name, null);
    }
}
