/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database.tables.records;


import com.csc680.orbit.database.tables.AccountLinkTeacher;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountLinkTeacherRecord extends UpdatableRecordImpl<AccountLinkTeacherRecord> implements Record5<Integer, Date, String, Integer, Integer> {

    private static final long serialVersionUID = 172223443;

    /**
     * Setter for <code>orbit.account_link_teacher.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orbit.account_link_teacher.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orbit.account_link_teacher.Date_Linked</code>.
     */
    public void setDateLinked(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>orbit.account_link_teacher.Date_Linked</code>.
     */
    public Date getDateLinked() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>orbit.account_link_teacher.Active</code>.
     */
    public void setActive(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orbit.account_link_teacher.Active</code>.
     */
    public String getActive() {
        return (String) get(2);
    }

    /**
     * Setter for <code>orbit.account_link_teacher.User_ID</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>orbit.account_link_teacher.User_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>orbit.account_link_teacher.Teacher_ID</code>.
     */
    public void setTeacherId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>orbit.account_link_teacher.Teacher_ID</code>.
     */
    public Integer getTeacherId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Date, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Date, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AccountLinkTeacher.ACCOUNT_LINK_TEACHER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return AccountLinkTeacher.ACCOUNT_LINK_TEACHER.DATE_LINKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AccountLinkTeacher.ACCOUNT_LINK_TEACHER.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return AccountLinkTeacher.ACCOUNT_LINK_TEACHER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return AccountLinkTeacher.ACCOUNT_LINK_TEACHER.TEACHER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getDateLinked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getTeacherId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDateLinked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTeacherId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacherRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacherRecord value2(Date value) {
        setDateLinked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacherRecord value3(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacherRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacherRecord value5(Integer value) {
        setTeacherId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountLinkTeacherRecord values(Integer value1, Date value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountLinkTeacherRecord
     */
    public AccountLinkTeacherRecord() {
        super(AccountLinkTeacher.ACCOUNT_LINK_TEACHER);
    }

    /**
     * Create a detached, initialised AccountLinkTeacherRecord
     */
    public AccountLinkTeacherRecord(Integer id, Date dateLinked, String active, Integer userId, Integer teacherId) {
        super(AccountLinkTeacher.ACCOUNT_LINK_TEACHER);

        set(0, id);
        set(1, dateLinked);
        set(2, active);
        set(3, userId);
        set(4, teacherId);
    }
}
