/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database.tables.records;


import com.csc680.orbit.database.tables.School;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchoolRecord extends UpdatableRecordImpl<SchoolRecord> implements Record7<Integer, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1912183192;

    /**
     * Setter for <code>orbit.school.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orbit.school.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orbit.school.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orbit.school.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orbit.school.Address_1</code>.
     */
    public void setAddress_1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orbit.school.Address_1</code>.
     */
    public String getAddress_1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>orbit.school.Address_2</code>.
     */
    public void setAddress_2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orbit.school.Address_2</code>.
     */
    public String getAddress_2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>orbit.school.City</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>orbit.school.City</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>orbit.school.State</code>.
     */
    public void setState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>orbit.school.State</code>.
     */
    public String getState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>orbit.school.Zip_Code</code>.
     */
    public void setZipCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>orbit.school.Zip_Code</code>.
     */
    public String getZipCode() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return School.SCHOOL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return School.SCHOOL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return School.SCHOOL.ADDRESS_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return School.SCHOOL.ADDRESS_2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return School.SCHOOL.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return School.SCHOOL.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return School.SCHOOL.ZIP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAddress_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAddress_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddress_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddress_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value3(String value) {
        setAddress_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value4(String value) {
        setAddress_2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value5(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value6(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value7(String value) {
        setZipCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchoolRecord
     */
    public SchoolRecord() {
        super(School.SCHOOL);
    }

    /**
     * Create a detached, initialised SchoolRecord
     */
    public SchoolRecord(Integer id, String name, String address_1, String address_2, String city, String state, String zipCode) {
        super(School.SCHOOL);

        set(0, id);
        set(1, name);
        set(2, address_1);
        set(3, address_2);
        set(4, city);
        set(5, state);
        set(6, zipCode);
    }
}
