/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database.tables.records;


import com.csc680.orbit.database.tables.SchoolStudent;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchoolStudentRecord extends UpdatableRecordImpl<SchoolStudentRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -695521573;

    /**
     * Setter for <code>orbit.school_student.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orbit.school_student.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orbit.school_student.School_ID</code>.
     */
    public void setSchoolId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>orbit.school_student.School_ID</code>.
     */
    public Integer getSchoolId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>orbit.school_student.Student_ID</code>.
     */
    public void setStudentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>orbit.school_student.Student_ID</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SchoolStudent.SCHOOL_STUDENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SchoolStudent.SCHOOL_STUDENT.SCHOOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SchoolStudent.SCHOOL_STUDENT.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolStudentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolStudentRecord value2(Integer value) {
        setSchoolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolStudentRecord value3(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolStudentRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchoolStudentRecord
     */
    public SchoolStudentRecord() {
        super(SchoolStudent.SCHOOL_STUDENT);
    }

    /**
     * Create a detached, initialised SchoolStudentRecord
     */
    public SchoolStudentRecord(Integer id, Integer schoolId, Integer studentId) {
        super(SchoolStudent.SCHOOL_STUDENT);

        set(0, id);
        set(1, schoolId);
        set(2, studentId);
    }
}
