/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database.tables.records;


import com.csc680.orbit.database.tables.Student;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> {

    private static final long serialVersionUID = -1181295522;

    /**
     * Setter for <code>orbit.student.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orbit.student.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orbit.student.First_Name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orbit.student.First_Name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orbit.student.Last_Name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orbit.student.Last_Name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>orbit.student.Date_Of_Birth</code>.
     */
    public void setDateOfBirth(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orbit.student.Date_Of_Birth</code>.
     */
    public String getDateOfBirth() {
        return (String) get(3);
    }

    /**
     * Setter for <code>orbit.student.SSN</code>.
     */
    public void setSsn(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>orbit.student.SSN</code>.
     */
    public String getSsn() {
        return (String) get(4);
    }

    /**
     * Setter for <code>orbit.student.Address_1</code>.
     */
    public void setAddress_1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>orbit.student.Address_1</code>.
     */
    public String getAddress_1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>orbit.student.Address_2</code>.
     */
    public void setAddress_2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>orbit.student.Address_2</code>.
     */
    public String getAddress_2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>orbit.student.City</code>.
     */
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>orbit.student.City</code>.
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>orbit.student.State</code>.
     */
    public void setState(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>orbit.student.State</code>.
     */
    public String getState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>orbit.student.Zip_Code</code>.
     */
    public void setZipCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>orbit.student.Zip_Code</code>.
     */
    public String getZipCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>orbit.student.Grade</code>.
     */
    public void setGrade(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>orbit.student.Grade</code>.
     */
    public String getGrade() {
        return (String) get(10);
    }

    /**
     * Setter for <code>orbit.student.Mother_First_Name</code>.
     */
    public void setMotherFirstName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_First_Name</code>.
     */
    public String getMotherFirstName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>orbit.student.Mother_Last_Name</code>.
     */
    public void setMotherLastName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Last_Name</code>.
     */
    public String getMotherLastName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>orbit.student.Mother_SSN</code>.
     */
    public void setMotherSsn(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_SSN</code>.
     */
    public String getMotherSsn() {
        return (String) get(13);
    }

    /**
     * Setter for <code>orbit.student.Mother_Address_1</code>.
     */
    public void setMotherAddress_1(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Address_1</code>.
     */
    public String getMotherAddress_1() {
        return (String) get(14);
    }

    /**
     * Setter for <code>orbit.student.Mother_Address_2</code>.
     */
    public void setMotherAddress_2(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Address_2</code>.
     */
    public String getMotherAddress_2() {
        return (String) get(15);
    }

    /**
     * Setter for <code>orbit.student.Mother_City</code>.
     */
    public void setMotherCity(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_City</code>.
     */
    public String getMotherCity() {
        return (String) get(16);
    }

    /**
     * Setter for <code>orbit.student.Mother_State</code>.
     */
    public void setMotherState(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_State</code>.
     */
    public String getMotherState() {
        return (String) get(17);
    }

    /**
     * Setter for <code>orbit.student.Mother_Zip_Code</code>.
     */
    public void setMotherZipCode(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Zip_Code</code>.
     */
    public String getMotherZipCode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>orbit.student.Mother_Home_Phone</code>.
     */
    public void setMotherHomePhone(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Home_Phone</code>.
     */
    public String getMotherHomePhone() {
        return (String) get(19);
    }

    /**
     * Setter for <code>orbit.student.Mother_Cell_Phone</code>.
     */
    public void setMotherCellPhone(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Cell_Phone</code>.
     */
    public String getMotherCellPhone() {
        return (String) get(20);
    }

    /**
     * Setter for <code>orbit.student.Mother_Email</code>.
     */
    public void setMotherEmail(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>orbit.student.Mother_Email</code>.
     */
    public String getMotherEmail() {
        return (String) get(21);
    }

    /**
     * Setter for <code>orbit.student.Father_First_Name</code>.
     */
    public void setFatherFirstName(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>orbit.student.Father_First_Name</code>.
     */
    public String getFatherFirstName() {
        return (String) get(22);
    }

    /**
     * Setter for <code>orbit.student.Father_Last_Name</code>.
     */
    public void setFatherLastName(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Last_Name</code>.
     */
    public String getFatherLastName() {
        return (String) get(23);
    }

    /**
     * Setter for <code>orbit.student.Father_SSN</code>.
     */
    public void setFatherSsn(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>orbit.student.Father_SSN</code>.
     */
    public String getFatherSsn() {
        return (String) get(24);
    }

    /**
     * Setter for <code>orbit.student.Father_Address_1</code>.
     */
    public void setFatherAddress_1(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Address_1</code>.
     */
    public String getFatherAddress_1() {
        return (String) get(25);
    }

    /**
     * Setter for <code>orbit.student.Father_Address_2</code>.
     */
    public void setFatherAddress_2(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Address_2</code>.
     */
    public String getFatherAddress_2() {
        return (String) get(26);
    }

    /**
     * Setter for <code>orbit.student.Father_City</code>.
     */
    public void setFatherCity(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>orbit.student.Father_City</code>.
     */
    public String getFatherCity() {
        return (String) get(27);
    }

    /**
     * Setter for <code>orbit.student.Father_State</code>.
     */
    public void setFatherState(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>orbit.student.Father_State</code>.
     */
    public String getFatherState() {
        return (String) get(28);
    }

    /**
     * Setter for <code>orbit.student.Father_Zip_Code</code>.
     */
    public void setFatherZipCode(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Zip_Code</code>.
     */
    public String getFatherZipCode() {
        return (String) get(29);
    }

    /**
     * Setter for <code>orbit.student.Father_Home_Phone</code>.
     */
    public void setFatherHomePhone(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Home_Phone</code>.
     */
    public String getFatherHomePhone() {
        return (String) get(30);
    }

    /**
     * Setter for <code>orbit.student.Father_Cell_Phone</code>.
     */
    public void setFatherCellPhone(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Cell_Phone</code>.
     */
    public String getFatherCellPhone() {
        return (String) get(31);
    }

    /**
     * Setter for <code>orbit.student.Father_Email</code>.
     */
    public void setFatherEmail(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>orbit.student.Father_Email</code>.
     */
    public String getFatherEmail() {
        return (String) get(32);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer id, String firstName, String lastName, String dateOfBirth, String ssn, String address_1, String address_2, String city, String state, String zipCode, String grade, String motherFirstName, String motherLastName, String motherSsn, String motherAddress_1, String motherAddress_2, String motherCity, String motherState, String motherZipCode, String motherHomePhone, String motherCellPhone, String motherEmail, String fatherFirstName, String fatherLastName, String fatherSsn, String fatherAddress_1, String fatherAddress_2, String fatherCity, String fatherState, String fatherZipCode, String fatherHomePhone, String fatherCellPhone, String fatherEmail) {
        super(Student.STUDENT);

        set(0, id);
        set(1, firstName);
        set(2, lastName);
        set(3, dateOfBirth);
        set(4, ssn);
        set(5, address_1);
        set(6, address_2);
        set(7, city);
        set(8, state);
        set(9, zipCode);
        set(10, grade);
        set(11, motherFirstName);
        set(12, motherLastName);
        set(13, motherSsn);
        set(14, motherAddress_1);
        set(15, motherAddress_2);
        set(16, motherCity);
        set(17, motherState);
        set(18, motherZipCode);
        set(19, motherHomePhone);
        set(20, motherCellPhone);
        set(21, motherEmail);
        set(22, fatherFirstName);
        set(23, fatherLastName);
        set(24, fatherSsn);
        set(25, fatherAddress_1);
        set(26, fatherAddress_2);
        set(27, fatherCity);
        set(28, fatherState);
        set(29, fatherZipCode);
        set(30, fatherHomePhone);
        set(31, fatherCellPhone);
        set(32, fatherEmail);
    }
}
