/*
 * This file is generated by jOOQ.
*/
package com.csc680.orbit.database;


import com.csc680.orbit.database.tables.AccountLinkStudent;
import com.csc680.orbit.database.tables.AccountLinkTeacher;
import com.csc680.orbit.database.tables.Assignment;
import com.csc680.orbit.database.tables.Course;
import com.csc680.orbit.database.tables.Grade;
import com.csc680.orbit.database.tables.Message;
import com.csc680.orbit.database.tables.Picture;
import com.csc680.orbit.database.tables.Role;
import com.csc680.orbit.database.tables.Schedule;
import com.csc680.orbit.database.tables.School;
import com.csc680.orbit.database.tables.SchoolStudent;
import com.csc680.orbit.database.tables.Student;
import com.csc680.orbit.database.tables.Teacher;
import com.csc680.orbit.database.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in orbit
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>orbit.account_link_student</code>.
     */
    public static final AccountLinkStudent ACCOUNT_LINK_STUDENT = com.csc680.orbit.database.tables.AccountLinkStudent.ACCOUNT_LINK_STUDENT;

    /**
     * The table <code>orbit.account_link_teacher</code>.
     */
    public static final AccountLinkTeacher ACCOUNT_LINK_TEACHER = com.csc680.orbit.database.tables.AccountLinkTeacher.ACCOUNT_LINK_TEACHER;

    /**
     * The table <code>orbit.assignment</code>.
     */
    public static final Assignment ASSIGNMENT = com.csc680.orbit.database.tables.Assignment.ASSIGNMENT;

    /**
     * The table <code>orbit.course</code>.
     */
    public static final Course COURSE = com.csc680.orbit.database.tables.Course.COURSE;

    /**
     * The table <code>orbit.grade</code>.
     */
    public static final Grade GRADE = com.csc680.orbit.database.tables.Grade.GRADE;

    /**
     * The table <code>orbit.message</code>.
     */
    public static final Message MESSAGE = com.csc680.orbit.database.tables.Message.MESSAGE;

    /**
     * The table <code>orbit.picture</code>.
     */
    public static final Picture PICTURE = com.csc680.orbit.database.tables.Picture.PICTURE;

    /**
     * The table <code>orbit.role</code>.
     */
    public static final Role ROLE = com.csc680.orbit.database.tables.Role.ROLE;

    /**
     * The table <code>orbit.schedule</code>.
     */
    public static final Schedule SCHEDULE = com.csc680.orbit.database.tables.Schedule.SCHEDULE;

    /**
     * The table <code>orbit.school</code>.
     */
    public static final School SCHOOL = com.csc680.orbit.database.tables.School.SCHOOL;

    /**
     * The table <code>orbit.school_student</code>.
     */
    public static final SchoolStudent SCHOOL_STUDENT = com.csc680.orbit.database.tables.SchoolStudent.SCHOOL_STUDENT;

    /**
     * The table <code>orbit.student</code>.
     */
    public static final Student STUDENT = com.csc680.orbit.database.tables.Student.STUDENT;

    /**
     * The table <code>orbit.teacher</code>.
     */
    public static final Teacher TEACHER = com.csc680.orbit.database.tables.Teacher.TEACHER;

    /**
     * The table <code>orbit.user</code>.
     */
    public static final User USER = com.csc680.orbit.database.tables.User.USER;
}
