/*
 * This file is generated by jOOQ.
*/
package database;


import database.tables.AccountLink;
import database.tables.Assignment;
import database.tables.Course;
import database.tables.Grade;
import database.tables.Message;
import database.tables.Picture;
import database.tables.Schedule;
import database.tables.Student;
import database.tables.Teacher;
import database.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in orbit
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>orbit.account_link</code>.
     */
    public static final AccountLink ACCOUNT_LINK = database.tables.AccountLink.ACCOUNT_LINK;

    /**
     * The table <code>orbit.assignment</code>.
     */
    public static final Assignment ASSIGNMENT = database.tables.Assignment.ASSIGNMENT;

    /**
     * The table <code>orbit.course</code>.
     */
    public static final Course COURSE = database.tables.Course.COURSE;

    /**
     * The table <code>orbit.grade</code>.
     */
    public static final Grade GRADE = database.tables.Grade.GRADE;

    /**
     * The table <code>orbit.message</code>.
     */
    public static final Message MESSAGE = database.tables.Message.MESSAGE;

    /**
     * The table <code>orbit.picture</code>.
     */
    public static final Picture PICTURE = database.tables.Picture.PICTURE;

    /**
     * The table <code>orbit.schedule</code>.
     */
    public static final Schedule SCHEDULE = database.tables.Schedule.SCHEDULE;

    /**
     * The table <code>orbit.student</code>.
     */
    public static final Student STUDENT = database.tables.Student.STUDENT;

    /**
     * The table <code>orbit.teacher</code>.
     */
    public static final Teacher TEACHER = database.tables.Teacher.TEACHER;

    /**
     * The table <code>orbit.user</code>.
     */
    public static final User USER = database.tables.User.USER;
}
